SeniorProjectWorkGroup/graceShopper

- package.json
Changed the app name so that "npm test" passes all initial 7 tests
> changed app name to pass initial tests

- server/db/models/index.js
- server/db/models/product.js
> Product model added and imported into index

- server/db/models/product.spec.js
new test spec file created testing multiple aspects of the product model
> added test spec file for product model

- server/db/models/category.js
- server/db/models/category.spec.js
- server/db/models/index.js
> Create category model

- package-lock.json
- server/db/models/category.js
- server/db/models/category.spec.js
- server/db/models/index.js
Fixed Tests and Category Models
> adjusted Category Model and tests

- client/store/index.js
- client/store/products/productsList.js
- client/store/products/singleProduct.js
Created Product List Reducer 
Created Single Product Reducer
> Redux prod#34

- client/components/Product.js
- client/components/ProductList.js
- client/components/index.js
- client/routes.js
> showing all products rendered

- client/app.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
Added CategorySideBar to every page
Fixed a merge error
Added a Products button to the navbar
> Category filter#43

- client/components/CategorySideBar.js
- client/components/Product.js
- client/components/ProductList.js
- client/routes.js
- client/store/category.js
- client/store/index.js
- client/store/products/displayedProducts.js
- client/store/products/productsList.js
- server/api/products.js
Can filter products by category
Added displayedProducts reducer
> can filter products by category

- server/db/models/index.js
- server/db/models/order.js
- server/db/models/order.spec.js
modeled order in DB and created test spec for model
completes #50
> order model and test complete

- client/components/Product-Forms/EditProductForm.js
- client/components/navbar.js
Added Dynamic Loading to Edit Product Form
> quick fix, added dynamic loading to edit forms

- script/data/order.json
- script/data/user.json
- script/seed.js
Added seed file for User
Added seed file for Order but not hooked up yet b/c Order model is not ready
> added seeds for users and orders but order model not hooked up yet

- script/data/order.json
- script/data/review.json
- script/seed.js
- server/api/index.js
- server/api/products.js
- server/api/reviews.js
- server/api/reviews.spec.js
- server/db/models/index.js
- server/db/models/review.js
Added Review model
Added /api/reviews get routes with test
Added seeding for Review
Hooked up seeding for Order
> Reviews#62

- client/components/auth-form.spec.js
- client/store/cartReducer.js
Created Reducer for Cart w/o thunks
> Reducer for cart#63

- server/api/helper.js
- server/api/products.js
> corrected helper functions and product api routes for admin checks

- client/components/Product-Forms/AddProductForm.spec.js
- client/store/cartReducer.js
- client/store/cartReducer.spec.js
- client/store/user.js
- public/index.html
- server/api/cart.js
- server/api/cart.spec.js
- server/api/index.js
- server/api/lineItem.js
- server/api/lineitem.spec.js
- server/auth/google.js
- server/auth/index.js
- server/db/models/cart.js
- server/db/models/index.js
- server/db/models/lineItem.js
- server/db/models/lineitem.spec.js
> Added Cart Reducer, API and Tests, added Cart Id to req.user object on login/signup

- client/components/Product-Forms/AddProductForm.js
- client/components/Product-Forms/AddProductForm.spec.js
- client/store/cartReducer.spec.js
> Last pull for Forms

- .gitignore
- script/seedLarp.js
Fixed category filtering. Need to re-seed the larp data.
Added public/img to .gitignore
> fixed category filtering

- client/components/Admin/AdminUserManagement.js
- client/components/Admin/UserListing.js
- client/components/ProductList.js
- client/routes.js
- client/store/index.js
- client/store/userList.js
- client/store/userListReducer.js
- server/api/cart.spec.js
- server/api/helper.js
- server/api/users.js
created userList reducer and Api 
Created UserListing and AdminUserManagement Components 
Added buttons and hooked up routes so that admin can edit and delete users through form
> Admin user edit#88

- .gitignore
- client/components/Cart.js
- client/components/Product-Forms/AddProductForm.js
- client/components/Product-Forms/AddProductForm.spec.js
- client/components/navbar.js
- client/routes.js
- client/store/cartReducer.spec.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> attempted need fix (brendon to look at)

- client/components/Cart.js
- client/components/CartItem.js
- client/store/cartReducer.js
- server/api/lineItem.js
Eager Load in GET /:itemId
Add fetch Cart in component did mount, component Did Update is a backup 
Added Quantity Btns in CartItem
Added PutItem and EDIT_ITEM in cartReducer
close #75
> Added Edit Quantity Buttons

- client/components/Cart.js
- client/components/CartItem.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> able to remove items from cart and db

- client/components/navbar.js
Link to Users View on nav bar if user is admin added
> Added User View Link

- client/components/Cart.js
- client/utils.js
calculateTax and total function
> Added Utils File with Calculate Tax And Total Function

- client/components/Cart.js
- client/components/Product.js
- public/style.css
- server/api/lineItem.js
Added Add to cart button on Product Listing
> addToCart Added

- client/routes.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> fixed syntax error

- client/components/CheckoutForm.js
- server/api/orders.js
- server/db/models/order.js
order creation bug fixed to include user id . orders now render for user
> create orders fixed to include user id in api and in db model

- client/components/Product.js
- client/components/ProductList.js
- client/components/SingleProductPage.js
- client/store/lineItemReducer.js
- server/api/lineItem.js
addToCart button works on single product page.
> addToCart on single product page works.

- client/components/CategorySideBar.js
- client/components/Orders/AllOrders.js
- client/components/Orders/SingleOrder.js
- client/components/Orders/UserOrders.js
- client/components/Product-Forms/orderUnit.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- public/index.html
- public/style.css
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> Styling for products#141
